default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: match_db
  port: 5432
  username: admin
  password: password

development:
  <<: *default
  database: match_development

production:
  <<: *default
  database: match_production
  username: admin
  password: <%= ENV["match_DATABASE_PASSWORD"] %>