services:
  match_web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: match_web
    image: match_web:0.1
    command: >
      bash -c "
        bundle install &&
        rm -f /rails/tmp/pids/server.pid &&
        bundle exec rake db:create &&
        bundle exec rake db:migrate &&
        ./bin/rails db:seed &&
        ./bin/rails assets:precompile &&
        ./bin/rails server -b 0.0.0.0 -p 3000
      "
    environment:
      - GMAIL_USERNAME=swbt.tatiya@gmail.com  # Add your Gmail username
      - GMAIL_APP_PASSWORD=abxp btrh qmdc padd  # Add your Google App Password, wrapped in quotes
      - REDIS_URL=redis://redis:6379/1  # Ensure Rails knows how to connect to Redis

    ports:
      - "3333:3000"
      
    platform: linux/amd64

    networks:
      - match_network
    volumes:
      - ./:/rails
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - match_network

networks:
  match_network:
    external: true

volumes:
  redis-data: