services:
  match_db:
    image: postgres:latest
    container_name: match_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - match_network

  match_pgadmin:
    image: dpage/pgadmin4
    container_name: match_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8333:80"
    depends_on:
      - match_db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - match_network

volumes:
  pgadmin_data:

networks:
  match_network:
    external: true
